In [98]:
import pandas as pd

In [99]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [100]:
df=pd.read_csv("play_tennis.csv")

In [101]:
df.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [102]:
df.drop(columns=["day"],inplace=True)

In [103]:
df

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [104]:
# problem 1
#outlook=Sunny, temp=hot , humidith=high , wind=weak
# play or no play?

In [105]:
#solution
#p(yes/Sunny,hot,high,weak)=p(sunny/yes) * p(hot/yes) * p(high/yes) * p(weak/yes) * p(yes)

#p(no/Sunny,hot,high,weak)=p(sunny/no) * p(hot/no) * p(high/no) * p(weak/no) * p(no)

# compare and decide using the maximum posteriori rule

In [106]:
df["play"].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [107]:
pyes=9/14
pno=5/14

In [108]:
#outlook
pd.crosstab(df["outlook"],df["play"])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [109]:
psunnyy=3/9
povercasty=4/9
prainy=2/9

psunnyn=2/5
povercastn=0
prainn=3/5

In [110]:
#temp
pd.crosstab(df["temp"],df["play"])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [111]:
pcooly=3/9
photy=2/9
pmildy=4/9

pcooln=1/5
photn=2/5
pmildn=4/5

In [112]:
#humidity
pd.crosstab(df["humidity"],df["play"])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [113]:
phighy=3/9
pnormaly=6/9

phighn=4/5
pnormaln=1/5

In [114]:
#wind
pd.crosstab(df["wind"],df["play"])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [115]:
pstrongy=3/14
pweaky=6/14

pstrongn=3/5
pweakn=2/5

In [116]:
#outlook=Sunny, temp=hot , humidith=high , wind=weak
pyes_=psunnyy*photy*phighy*pweaky*pyes
pyes_

0.006802721088435374

In [117]:
pno_=psunnyn*photn*phighn*pweakn*pno
pno_

0.01828571428571429

In [ ]:
#so basically the prob of no is high that's why output will bw no